config/routes.rb
require 'sidekiq/web'
Dcisample::Application.routes.draw do

  devise_for :users

  resources :auctions do
    resources :bids do
      collection do
        post :buy
      end
    end
  end

  root :to => 'auctions#index'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/address.rb
class Address < Struct.new(:country, :city, :street, :postal_code)
end

app/models/auction.rb
class Auction < ActiveRecord::Base
  attr_accessible :seller, :item, :buy_it_now_price, :status, :end_date, :extendable

  belongs_to :item
  belongs_to :winner, :class_name => 'User'
  belongs_to :seller, :class_name => 'User'
  has_many :bids

  PENDING = 'pending'
  STARTED = 'started'
  CLOSED = 'closed'
  CANCELED = 'canceled'
  validates :status, inclusion: {in: [PENDING, STARTED, CLOSED, CANCELED]}

  validates :item, presence: true
  validates :seller, presence: true
  validates :end_date, presence: true
  validates :buy_it_now_price, :numericality => true

  validate :buyer_and_seller_are_different
  validate :end_date_period

  def start
    self.status = STARTED
    save!
  end

  def close
    self.status = CLOSED
    save!
  end

  def started?
    status == STARTED
  end

  def last_bid
    bids.last
  end

  def extend_end_date_for interval
    self.end_date = interval.since self.end_date
    save!
  end

  def assign_winner bidder
    self.winner = bidder
    close
  rescue ActiveRecord::RecordInvalid => e
    raise InvalidRecordException.new(e.record.errors.full_messages)
  end

  def make_bid bidder, amount
    bids.create! user: bidder, amount: amount
  rescue ActiveRecord::RecordInvalid => e
    raise InvalidRecordException.new(e.record.errors.full_messages)
  end

  def self.make attrs
    create! attrs.merge(status: PENDING)
  rescue ActiveRecord::RecordInvalid => e
    raise InvalidRecordException.new(e.record.errors.full_messages)
  end

  private

  def end_date_period
    errors.add(:end_date, "must be in the future") if end_date && end_date < DateTime.current
  end

  def buyer_and_seller_are_different
    errors.add(:base, "can't be equal to seller") if seller_id == winner_id
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  attr_accessible :amount, :user

  belongs_to :user

  validates :user, presence: true
  validates :amount, :numericality => true
end

app/models/create_auction.rb
class CreateAuction
  include Context

  attr_reader :seller, :auction_creator

  def self.create user, auction_params
    c = CreateAuction.new user, auction_params
    c.create
  end

  def initialize user, auction_params
    @seller = user.extend Seller
    @auction_creator = auction_params.extend AuctionCreator
  end

  def create
    in_context do
      return {auction: seller.start_auction}
    end
  rescue InvalidRecordException => e
    {errors: e.errors}
  end

  module Seller
    include ContextAccessor

    def start_auction
      auction = context.auction_creator.create_auction self
      auction.start
      auction
    end
  end

  module AuctionCreator
    include ContextAccessor

    def create_auction seller
      item = create_item
      Auction.make(seller, item, buy_it_now_price)
    end

    def create_item
      Item.make(item_name, item_description)
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :description

  validates :name, presence: true

  def self.make name, description
    Item.create!(name: name, description: description)
  rescue ActiveRecord::RecordInvalid => e
    raise InvalidRecordException.new(e.record.errors.full_messages)
  end
end

app/models/test.rb
class Test
  def self.foo
    "bar"
  end
end

app/models/user.rb
require 'devise'
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  validates :name, presence: true
  validates :email, presence: true

  def address
    Address.new(address_country, address_city, address_street, address_postal_code)
  end

  def address= address
    self[:address_country] = address.country
    self[:address_city] = address.city
    self[:address_street] = address.street
    self[:address_postal_code] = address.postal_code
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @auctions = AuctionsPresenter.new(Auction.all, current_user, view_context)
  end

  def show
    auction_to_show = Auction.find(params[:id])
    @auction = AuctionPresenter.new(auction_to_show, current_user, view_context)
  end

  def new
  end

  def create
    CreatingAuction.create(current_user, auction_params, self)
  end

  def create_on_success auction_id
    flash[:notice] = "Auction was successfully created."
    render json: {auction_path: auction_path(auction_id)}
  end

  def create_on_error errors
    render json: {:errors => errors}, status: :unprocessable_entity
  end

  private

  def auction_params
    AuctionParams.new(params[:auction_params])
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_filter :authenticate_user!

  def create
    Bidding.bid(current_user, bid_params, self)
  end

  def buy
    Bidding.buy(current_user, bid_params, self)
  end

  def create_on_success message
    flash[:notice] = message
    redirect_to auction_path(params[:auction_id])
  end

  def create_on_error errors
    flash[:error] = errors.join("\n")
    redirect_to auction_path(params[:auction_id])
  end

  private

  def bid_params
    p = {auction_id: params[:auction_id]}
    p = p.merge(params[:bid_params]) if params[:bid_params]
    BidParams.new(p)
  end
end

app/views/auctions/_bid.html.erb
<%= form_for BidParams.empty, url: auction_bids_path(auction_id), html:{class: "form-inline", style: 'float: left; margin-right: 20px;'} do |f| %>
  <div class="input-prepend input-append">
    <span class="add-on">$</span><%= f.text_field :amount, class: 'input-small' %><span class="add-on">.00</span>
  </div>
  <%= f.submit "Bid", class: "btn" %>
<% end %>

app/views/auctions/index.html.erb
<% content_for :title, "Auctions" %>

<h1>Auctions</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Seller</th>
    <th>Created at</th>
  </tr>
  </thead>
  <tbody>
  <% @auctions.each do |auction| %>
    <tr>
      <td><%= auction.id %></td>
      <td><%= link_to auction.item_name, auction_path(auction.id) %></td>
      <td><%= auction.seller_name %></td>
      <td><%= auction.created_at %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/auctions/new.html.erb
<% content_for :title, "Sell Item" %>

<%= form_for AuctionParams.empty, url: auctions_path, remote: true, html: {class: 'form-horizontal'} do |f| %>
  <legend>Sell Item</legend>

  <div id="auction_params_errors" class="alert alert-block alert-error" style="display:none;">
  </div>

  <fieldset>
    <div class="control-group">
      <%= f.label :item_name, "Name", class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :item_name %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :item_description, "Description", class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :item_description %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :buy_it_now_price, "Buy it now price", class: 'control-label' %>
      <div class="controls">
        <div class="input-prepend input-append">
          <span class="add-on">$</span><%= f.text_field :buy_it_now_price, class: 'input-small' %><span class="add-on">.00</span>
        </div>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :end_date, class: 'control-label' %>
      <div class="controls">
        <input type="text" id="auction_params_end_date" name="auction_params[end_date]">
      </div>
    </div>

    <div class="control-group">
      <div class="controls">
        <%= f.label :extendable, class: "checkbox" do %>
          <%= f.check_box :extendable %> Extendable
        <% end %>
      </div>
    </div>

  </fieldset>

  <div class="form-actions">
    <%= f.submit "Create", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/auctions/show.html.erb
<% content_for :title, @auction.item_name %>

<%= @auction.render_all_bids %>

<div id="buy_it_now_errors" class="alert alert-block alert-error" style="display:none;">
</div>

<h1><%= @auction.item_name %></h1>
<%= @auction.item_description %>

<dl class="dl-horizontal">
  <dt>Seller</dt>
  <dd><%= @auction.seller_name %></dd>
</dl>

<dl class="dl-horizontal">
  <dt>Buy it now price</dt>
  <dd><%= @auction.buy_it_now_price %></dd>
</dl>

<%= @auction.render_end_date %>

<%= @auction.render_winner %>

<%= @auction.render_last_bid %>

<div class="form-actions">
  <%= @auction.render_actions %>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">DCI-IN-RUBY: Auctions</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Auctions", auctions_path %></li>
          <li><%= link_to "Sell", new_auction_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=h yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<div class='container'>
  <%= render 'layouts/flash_messages' %>
  <%= yield %>
</div>

</body>
</html>